backend:
  name: git-gateway
  # repo: oparin10/atlas-gatsby-starter \
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}” [skip ci]"
    update: "Update {{collection}} “{{slug}} [skip ci]”"
    delete: "Delete {{collection}} “{{slug}} [skip ci]”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img
locale: pt
display_url: "https://atlascode.dev"
site_url: "https://atlascode.dev"
logo_url: https://i.imgur.com/gY3CoNL.png
slug:
  clean_accents: true

collections:
  - name: "services"
    editor:
      preview: false
    label: "Soluções"
    folder: "src/blog/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Content Type",
          name: "contentType",
          widget: "hidden",
          default: "servicePost",
        }
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "Post",
        }
      - { label: "Nome da solução", name: "title", widget: "string" }
      - { label: "Imagem principal", name: "featuredImage", widget: "image" }
      - {
          label: "Resumo (texto curto que aparecerá na página principal",
          name: "summary",
          widget: "text",
        }
      - {
          label: "Descrição (texto para a página do serviço específico)",
          name: "body",
          widget: "markdown",
        }
      - {
          label: "Lista de serviços oferecidos na solução",
          widget: "list",
          name: "benefits",
          allow_add: true,
          fields:
            [
              { label: Nome do benefício, name: benefitName, widget: string },
              {
                label: Descrição do benefício,
                name: benefitDescription,
                widget: text,
              },
            ],
        }
