name: Deploy to Netlify using Github Actions
"on":
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Netlify CLI 
        run: npm install netlify-cli -g
        
      - uses: actions/checkout@v2
      - name: Build
        working-directory: ./
        run: npm ci && npm run build
      
      - name: Deploy
        run: netlify deploy --prod --dir public --message "Site deployed from Githubactions ${{github.ref}}" --auth ${{ NETLIFY_AUTH_TOKEN }}  --site ${{ NETLIFY_APP_ID }}
      
      - name: Finish
        run: echo 'it just works'
